### ISSUE TITLE
https://github.com/fabius77/KeineAhnung/tree/Test/Konsolenanwendung_neu

### ISSUE THREAD

**Issue by FabiusGruener** [RobertNoack4/SchereSteinPapierEchseSpock#16]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RobertNoack4** [comment]
LERN FUCKING LESEN!
